### ISSUE TITLE
Missing description for the project field

### ISSUE THREAD

**Issue by KeithMnemonic** [SUSE/doc-public-cloud#1]
https://susedoc.github.io/doc-public-cloud/main/html/public-cloud/cha-images.html#var-pint

This content is missing the description of the project field when looking at Google images.  Was this intended or an oversight?

![image](https://user-images.githubusercontent.com/9559808/134061262-300572b8-8b3b-4f16-bd0f-4be90066c9d5.png)

**Comment by cwickert** [comment]
Sorry for the late response. 'project' was indeed an oversight.
