### ISSUE TITLE
more details about the images 

### ISSUE THREAD

**Issue by petersatsuse** [SUSE/doc-public-cloud#12]
there should be more details about 

- that we provide quite minimal images and depend on use case the customer need to add packages
- used disk layout (incl. swap handling)
- used filesystems 
   - (and why no btrfs, as this confuses customer and partners sometimes, as a snapshot of a vm works differently as on a fs)
- size of the os disk (as its different in different clouds, why?)
- details of the package selection (and added special parts e.g. for HPC if there are some)
- details of the activated services
- and if its identical on all major clouds (except some csp needs)
- resize of images (at the different csp's)
- tips/help to create own golden images (suse tools or 3rd party) and there benefits/drawbacks
- hint to use SUMa for own patching with staging areas (or hint to suma docu)

**Comment by cwickert** [comment]
Thanks for this issue. I agree all of this would be very good to have, and not all of this is covered by #9 . Unfortunately don't have the information at hand right now. Can you provide me with some input on some of the points you raised? I'll try to incorporate it ASAP then. TIA!
